#!/bin/sh
i=0
dice="${1%%d*}"
sides="${1##*d}"
plusnum="${2##+}"
rollDice() {
	[ $i -lt "$dice" ] && { i="$(( i + 1 ))" ;
		[ -z "$plusnum" ] && echo "d$sides: $(shuf -i 1-"$sides" -n 1)" || echo "d$sides: $(($(shuf -i 1-"$sides" -n 1)+plusnum))";
		rollDice; } || exit 0
	}
rollDice
#while [ $i -lt $dice ]
#do
	#i="$(( $i + 1 ))"
	#[ -z "$plusnum" ] && echo "d$sides: $(shuf -i 1-$sides -n 1)" || echo "d$sides: $(($(shuf -i 1-$sides -n 1)+${2##+}))"
#done
